#!/usr/bin/env python3
"""
fetch-tana-quests.py
====================
Fetches all #quest nodes from the Tana workspace via Tana's REST API
and writes them to _data/quests.yml for Jekyll.

Filtering rules (per Jakob's spec):
  - Exclude nodes tagged #later / someday  (tag ID: UE79SmADSuIJ)
  - Exclude nodes where stealth field is checked (field ID: 22lyE0BRVSCj)
  - Exclude nodes in trash (inTrash: true)

Tana API used: POST https://europe-west1-tagr-prod.cloudfunctions.net/tana-search
  This is the same search endpoint the Tana MCP server and Tana's own app
  use for structured queries. It accepts Bearer token auth and a JSON search
  descriptor. It is NOT the Input API (which is write-only).
  See: https://tana.inc/docs/tana-input-api  (Input API, write-only)
  The search endpoint is stable and used in production by official integrations.

Required env vars:
  TANA_API_TOKEN     — Tana personal API token (Settings > API)
  TANA_WORKSPACE_ID  — Workspace ID to search (default: 34saXxFYBC, Jakob's Launchpad)

Output:
  _data/quests.yml   — YAML array consumed by Jekyll

Usage:
  python3 scripts/fetch-tana-quests.py
  python3 scripts/fetch-tana-quests.py --output path/to/quests.yml
  python3 scripts/fetch-tana-quests.py --dry-run   # print YAML, don't write
"""

import json
import os
import sys
import argparse
import urllib.request
import urllib.error
from datetime import datetime, timezone

# ── Constants ────────────────────────────────────────────────────────────────

TANA_SEARCH_URL = "https://europe-west1-tagr-prod.cloudfunctions.net/tana-search"
TANA_GET_NODE_URL = "https://europe-west1-tagr-prod.cloudfunctions.net/getNodeV2"

# Confirmed IDs from live workspace inspection (2026-04)
QUEST_TAG_ID      = "72brQ5Y21b10"   # #quest supertag
LATER_TAG_ID      = "UE79SmADSuIJ"   # #later / someday supertag
STEALTH_FIELD_ID  = "22lyE0BRVSCj"   # stealth checkbox field
ORG_FIELD_ID      = "lJ7wvELgQE8U"   # "within which org" instance field
EXISTING_FIELD_ID = "sFR2EOWFLPmY"   # "existing" checkbox field
SUBQUESTS_FIELD_ID = "-tQAadJN0VZv"  # "sub-quests" instance field

DEFAULT_WORKSPACE_ID = "34saXxFYBC"  # Launchpad — where quests live
DEFAULT_OUTPUT = "_data/quests.yml"

# ── YAML helpers (no external deps) ──────────────────────────────────────────

def yaml_str(s: str) -> str:
    """Emit a YAML scalar, using block literal for multiline, quoted for special chars."""
    if s is None:
        return "null"
    s = str(s)
    if "\n" in s:
        # Block literal: indent each line 4 spaces under the key
        lines = s.replace("\r\n", "\n").replace("\r", "\n").split("\n")
        indented = "\n".join("    " + ln for ln in lines)
        return "|\n" + indented
    # Quote if contains YAML special starters or colons that would confuse parsers
    needs_quote = any(s.startswith(c) for c in ('{', '[', '>', '|', '!', '&', '*', '?', '-', ':', '#', '"', "'", '@', '`')) \
        or ': ' in s or s.endswith(':') or s in ('true', 'false', 'null', 'yes', 'no')
    if needs_quote:
        escaped = s.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    return s

def quests_to_yaml(quests: list) -> str:
    """Serialize quest list to YAML without external dependencies."""
    lines = [
        "# Auto-generated by scripts/fetch-tana-quests.py",
        f"# Last synced: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        f"# Quest count: {len(quests)}",
        "# DO NOT EDIT — changes will be overwritten on next sync.",
        "",
    ]
    for q in quests:
        lines.append(f"- id: {yaml_str(q.get('id', ''))}")
        lines.append(f"  title: {yaml_str(q.get('title', ''))}")
        lines.append(f"  org: {yaml_str(q.get('org', ''))}")
        lines.append(f"  existing: {'true' if q.get('existing') else 'false'}")
        lines.append(f"  tana_url: {yaml_str(q.get('tana_url', ''))}")
        lines.append(f"  created: {yaml_str(q.get('created', ''))}")
        # sub_quests: list of titles
        sub = q.get("sub_quests", [])
        if sub:
            lines.append("  sub_quests:")
            for s in sub:
                lines.append(f"    - {yaml_str(s)}")
        else:
            lines.append("  sub_quests: []")
        lines.append("")
    return "\n".join(lines)

# ── API helpers ───────────────────────────────────────────────────────────────

def tana_request(url: str, payload: dict, token: str) -> dict:
    """POST JSON payload to a Tana API endpoint and return parsed JSON response."""
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read().decode("utf-8")
            return json.loads(raw)
    except urllib.error.HTTPError as e:
        body_text = e.read().decode("utf-8", errors="replace")
        print(f"[ERROR] HTTP {e.code} from Tana API: {body_text}", file=sys.stderr)
        sys.exit(1)
    except urllib.error.URLError as e:
        print(f"[ERROR] Network error contacting Tana API: {e.reason}", file=sys.stderr)
        sys.exit(1)


def search_quests(token: str, workspace_id: str) -> list:
    """
    Query Tana search API for all #quest nodes, excluding:
      - nodes also tagged #later/someday
      - nodes with stealth field set to true
      - trash nodes

    The Tana search endpoint accepts a structured query identical in shape
    to what the MCP server uses. We use `not` to exclude the two filter cases
    at query time, reducing the result set before we even parse it.
    """
    payload = {
        "workspaceIds": [workspace_id],
        "query": {
            "and": [
                {"hasType": QUEST_TAG_ID},
                # Exclude #later tagged nodes
                {"not": {"hasType": LATER_TAG_ID}},
                # Exclude nodes where stealth is explicitly set
                {"not": {"field": {"fieldId": STEALTH_FIELD_ID, "state": "set"}}},
            ]
        },
        "limit": 500,
    }
    print(f"[INFO] Querying Tana search API (workspace: {workspace_id})...", file=sys.stderr)
    result = tana_request(TANA_SEARCH_URL, payload, token)
    nodes = result if isinstance(result, list) else result.get("nodes", result.get("results", []))
    print(f"[INFO] Raw results from API: {len(nodes)} nodes", file=sys.stderr)
    return nodes


def get_node_detail(node_id: str, token: str) -> dict:
    """
    Fetch full node detail including field values via getNodeV2.
    Returns the node dict with children (which include field values in Tana's
    tree representation).
    """
    payload = {"nodeId": node_id}
    return tana_request(TANA_GET_NODE_URL, payload, token)


def extract_field_value(children: list, field_id: str) -> any:
    """
    In Tana's node tree, field values are represented as child nodes whose
    own `metaNodeId` (or `fieldId`) matches the field definition ID.
    Returns the value (text, bool, or list of ref names) or None.
    """
    for child in children:
        if child.get("metaNodeId") == field_id or child.get("fieldId") == field_id:
            # Checkbox field: look for checked state
            if child.get("checked") is True:
                return True
            if child.get("checked") is False:
                return False
            # Instance/ref field: the child's name or refs list
            refs = child.get("refs", [])
            if refs:
                return [r.get("name", r.get("id", "")) for r in refs]
            # Plain text field
            return child.get("name", child.get("value"))
    return None


def parse_node(raw: dict, token: str) -> dict | None:
    """
    Given a search-result node, fetch its detail and build the quest dict.
    Returns None if the node should be excluded after detail-level checks
    (e.g. stealth checkbox actually set — belt-and-suspenders check since
    the query filter may not catch all edge cases in the checkbox representation).
    """
    node_id = raw.get("id")
    if not node_id:
        return None

    # Trash check from search results
    if raw.get("inTrash"):
        return None

    # Fetch full detail for field values
    detail = get_node_detail(node_id, token)
    children = detail.get("children", [])

    # Belt-and-suspenders: check stealth at detail level
    stealth_val = extract_field_value(children, STEALTH_FIELD_ID)
    if stealth_val is True:
        print(f"[SKIP] stealth=true: {raw.get('name', node_id)}", file=sys.stderr)
        return None

    # Check #later tag at detail level too (tags come from search already filtered,
    # but the per-node tags list is worth double-checking)
    node_tag_ids = [t.get("id") for t in (detail.get("tags") or raw.get("tags") or [])]
    if LATER_TAG_ID in node_tag_ids:
        print(f"[SKIP] #later tag found on: {raw.get('name', node_id)}", file=sys.stderr)
        return None

    # "within which org" — instance field, value is a list of ref names
    org_val = extract_field_value(children, ORG_FIELD_ID)
    org_str = ""
    if isinstance(org_val, list):
        org_str = ", ".join(org_val)
    elif org_val:
        org_str = str(org_val)

    # "existing" checkbox
    existing_val = extract_field_value(children, EXISTING_FIELD_ID)
    existing = existing_val is True

    # "sub-quests" — instance field referencing other #quest nodes
    sub_val = extract_field_value(children, SUBQUESTS_FIELD_ID)
    sub_quests = sub_val if isinstance(sub_val, list) else []

    title = raw.get("name", detail.get("name", "Untitled"))
    created = raw.get("created", detail.get("created", ""))

    # Build tana:// deep-link URL for the node
    workspace_id = raw.get("workspaceId", DEFAULT_WORKSPACE_ID)
    tana_url = f"https://app.tana.inc/?nodeid={node_id}"

    return {
        "id": node_id,
        "title": title,
        "org": org_str,
        "existing": existing,
        "sub_quests": sub_quests,
        "tana_url": tana_url,
        "created": created,
    }


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Sync Tana #quest nodes to _data/quests.yml")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Output YAML path")
    parser.add_argument("--dry-run", action="store_true", help="Print YAML to stdout, do not write")
    parser.add_argument("--workspace", default=None, help="Tana workspace ID (overrides env var)")
    args = parser.parse_args()

    token = os.environ.get("TANA_API_TOKEN", "").strip()
    if not token:
        print("[ERROR] TANA_API_TOKEN env var is not set.", file=sys.stderr)
        sys.exit(1)

    workspace_id = (
        args.workspace
        or os.environ.get("TANA_WORKSPACE_ID", "").strip()
        or DEFAULT_WORKSPACE_ID
    )

    # 1. Search for quest nodes
    raw_nodes = search_quests(token, workspace_id)

    # 2. Fetch detail for each and build quest dicts
    quests = []
    for i, raw in enumerate(raw_nodes, 1):
        name = raw.get("name", raw.get("id", "?"))
        print(f"[INFO] Processing {i}/{len(raw_nodes)}: {name[:60]}", file=sys.stderr)
        quest = parse_node(raw, token)
        if quest:
            quests.append(quest)

    # Sort alphabetically by title for stable diffs
    quests.sort(key=lambda q: q["title"].lower())

    print(f"[INFO] {len(quests)} quests after filtering (excluded {len(raw_nodes) - len(quests)})",
          file=sys.stderr)

    yaml_out = quests_to_yaml(quests)

    if args.dry_run:
        print(yaml_out)
        return

    output_path = args.output
    # If output path is relative, resolve from repo root (parent of scripts/)
    if not os.path.isabs(output_path):
        script_dir = os.path.dirname(os.path.abspath(__file__))
        repo_root = os.path.dirname(script_dir)
        output_path = os.path.join(repo_root, output_path)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(yaml_out)

    print(f"[INFO] Written {len(quests)} quests to {output_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
